set nocompatible
"set tags=~/.tags

"""""""""""""""""""" NeoBundle設定 """"""""""""""""""""
if has('vim_starting')
    set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))

NeoBundleFetch 'Shougo/neobundle.vim'

NeoBundle 'Shougo/vimproc', {
    \ 'build' : {
    \   'windows' : 'make -f make_mingw32.mak',
    \   'cygwin'  : 'make -f make_cygwin.mak',
    \   'mac'     : 'make -f make_mac.mak',
    \   'unix'    : 'make -f make_unix.mak',
    \ }
\ }

if has('lua') && (( v:version == 703 && has('patch885')) || (v:version >= 704))
    NeoBundle 'Shougo/neocomplete'
else
    NeoBundle 'Shougo/neocomplcache'
endif

NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/neomru.vim'
NeoBundle 'Townk/vim-autoclose'
NeoBundle 'mattn/emmet-vim'
NeoBundle 'grep.vim'
NeoBundle 'Shougo/neosnippet.vim'
NeoBundle 'Shougo/neosnippet-snippets'
NeoBundle 'Shougo/unite-outline'
NeoBundle 'rcmdnk/vim-markdown'
NeoBundle 'tomasr/molokai'
NeoBundle 'ujihisa/unite-colorscheme'

call neobundle#end()

filetype plugin indent on

NeoBundleCheck

"""""""""""""""""""" プラグイン毎の設定 """"""""""""""""""""
" Unite起動時にインサートモードで開始
"let g:unite_enable_start_insert = 1

" Uniteの各種ショートカット設定
" バッファ一覧
nnoremap <silent> ;ub :<C-u>Unite buffer<CR>
" ファイル一覧
nnoremap <silent> ;uf :<C-u>UniteWithBufferDir -buffer-name=files file<CR>
" レジスタ一覧
nnoremap <silent> ;ur :<C-u>Unite -buffer-name=register register<CR>
" 最近使用したファイル一覧
nnoremap <silent> ;um :<C-u>Unite file_mru<CR>
" 全部のせ
nnoremap <silent> ;ua :<C-u>UniteWithBufferDir -buffer-name=files buffer file_mru bookmark file<CR>

" Ctrl + o でタグアウトラインを表示
nnoremap <C-o> :<C-u>Unite outline<CR>

"""""""""""""""""""" プラグイン毎の設定完 """"""""""""""""""""

" display
" ----------------------
set number
set ruler
set cmdheight=2
set laststatus=2
set statusline=%<%f\ %m%r%h%w%{'['.(&fenc!=''?&fenc:&enc).']['.&ff.']'}%=%l,%c%V%8P
set title
set linespace=0
set wildmenu
set showcmd
"set textwidth=78
"set columns=100
"set lines=150

"
" color settings
"
syntax on
"colorscheme desert
"colorscheme zenburn
colorscheme molokai
highlight LineNr ctermfg=darkgrey
autocmd FileType php,ctp :set dictionary=~/.vim/dict/php.dict
setlocal omnifunc=syntaxcomplete#Complete

" edit
" ---------------------
set showmatch
set backspace=indent,eol,start
"バッファをクリップボードにコピー(for OSX)
set clipboard=unnamed,autoselect
set pastetoggle=<F12>
set guioptions+=a
"保存しないで他のファイルを表示することが出来るようにする
set hidden

" tab
" --------------------
set autoindent
"set cindent
"set expandtab
set tabstop=4
set smartindent
set shiftwidth=4
set shiftround
set nowrap

" mouse
" マウスモード有効
set mouse=a
" xterm, screen対応
set ttymouse=xterm2

"MacVimやGVimを利用する際にIMEがモードの切替でオフとなる設定
set imdisable

"全角スペースを　で表示
highlight JpSpace cterm=underline ctermfg=Blue guifg=Blue
au BufRead,BufNew * match JpSpace /　/

" show tab
set list
set listchars=tab:>-,trail:-

" サーチハイライトをESC二回で消す
nnoremap <ESC><ESC> :nohlsearch<CR><Esc>



"""""""""""""""""""" 言語毎の設定 """"""""""""""""""""
"ctagsのファイルをカレントディレクトリから検索して上位にあるものを読み込む
if has('path_extra')
    set tags+=tags;
endif

""""" PHP """""
" :makeでPHP構文チェック
au FileType php setlocal makeprg=php\ -l\ %
au FileType php setlocal errorformat=%m\ in\ %f\ on\ line\ %l
 
" 文字列の中のSQLをハイライト
let php_sql_query = 1
" Baselibメソッドのハイライト
let php_baselib = 1
" HTMLハイライト
let php_htmlInStrings = 1
" ], )の対応エラーをハイライト
let php_parent_error_close = 1
let php_parent_error_open = 1
"""""""""""""""""""" 言語毎の設定完 """"""""""""""""""""

set imdisable

